/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Chef: {
      address: "0x18E317A7D70d8fBf8e6E893616b52390EbBdb629",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AlreadyCooking",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidRecipeConfig",
          type: "error",
        },
        {
          inputs: [],
          name: "NotCooking",
          type: "error",
        },
        {
          inputs: [],
          name: "OnlyOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "RecipeNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [],
          name: "StillCooking",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroQuantity",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "cook",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "readyAt",
              type: "uint256",
            },
          ],
          name: "CookingStarted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "cook",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "DishClaimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "dishToken",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "prepTime",
              type: "uint256",
            },
          ],
          name: "RecipeAdded",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "address[]",
              name: "ingredientTokens",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "ingredientAmounts",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "prepTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "dishAmount",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "dishName",
              type: "string",
            },
            {
              internalType: "string",
              name: "dishSymbol",
              type: "string",
            },
          ],
          name: "addRecipe",
          outputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
          ],
          name: "claim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "cookingQuantity",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "cookingStartTime",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
          ],
          name: "getIngredients",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "token",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
              ],
              internalType: "struct Chef.Ingredient[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
          ],
          name: "getRecipe",
          outputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "prepTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "dishAmount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "dishToken",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "recipeCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "quantity",
              type: "uint256",
            },
          ],
          name: "startCooking",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "cook",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
          ],
          name: "timeUntilReady",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 769,
    },
    DishMarket: {
      address: "0xA7c59f010700930003b33aB25a7a0679C860f29c",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "_chef",
              type: "address",
            },
            {
              internalType: "address",
              name: "_farmManager",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AlreadyClaimed",
          type: "error",
        },
        {
          inputs: [],
          name: "AlreadyOffered",
          type: "error",
        },
        {
          inputs: [],
          name: "AskPriceExceedsCap",
          type: "error",
        },
        {
          inputs: [],
          name: "AskPriceTooHigh",
          type: "error",
        },
        {
          inputs: [],
          name: "EpochNotOver",
          type: "error",
        },
        {
          inputs: [],
          name: "InsufficientFunds",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidOfferIndex",
          type: "error",
        },
        {
          inputs: [],
          name: "NoOffers",
          type: "error",
        },
        {
          inputs: [],
          name: "NoRecipes",
          type: "error",
        },
        {
          inputs: [],
          name: "NotDemandedRecipe",
          type: "error",
        },
        {
          inputs: [],
          name: "NotWinner",
          type: "error",
        },
        {
          inputs: [],
          name: "NotYourOffer",
          type: "error",
        },
        {
          inputs: [],
          name: "OfferIsCurrentWinner",
          type: "error",
        },
        {
          inputs: [],
          name: "OnlyOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [],
          name: "TokenNotRegistered",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAmount",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAskPrice",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "winner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "askPrice",
              type: "uint256",
            },
          ],
          name: "EpochSettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "funder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Funded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "askPrice",
              type: "uint256",
            },
          ],
          name: "OfferSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "offerIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
          ],
          name: "OfferWithdrawn",
          type: "event",
        },
        {
          inputs: [],
          name: "EPOCH_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_WINNERS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "availableFunds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "chef",
          outputs: [
            {
              internalType: "contract Chef",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentDemand",
          outputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentEpoch",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentMinute",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentSecondDemand",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "epochState",
          outputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "secondRecipeId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "hasOffers",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "settledCount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "winnerIndex",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "winnerAskPrice",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "secondWinnerIndex",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "secondWinnerAskPrice",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "farmManager",
          outputs: [
            {
              internalType: "contract FarmManager",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
          ],
          name: "getDemandForMinute",
          outputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
          ],
          name: "getOffers",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "seller",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "askPrice",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "recipeId",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "claimed",
                  type: "bool",
                },
              ],
              internalType: "struct DishMarket.Offer[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
          ],
          name: "getWinnerCutoff",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "hasOffered",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
          ],
          name: "minuteState",
          outputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "hasOffers_",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "settled",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "winnerIndex",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "winnerAskPrice",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
          ],
          name: "secondDemandForEpoch",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "offerIndex",
              type: "uint256",
            },
          ],
          name: "settle",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "recipeId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "askPrice",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "submitOffer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "withdrawFunds",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "epoch",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "offerIndex",
              type: "uint256",
            },
          ],
          name: "withdrawOffer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 780,
    },
    FarmManager: {
      address: "0x4EE6eCAD1c2Dae9f525404De8555724e3c35d07B",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "_landAuction",
              type: "address",
            },
            {
              internalType: "address",
              name: "_seedShop",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ConfigAlreadyExists",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidFarmConfig",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidSeedAmount",
          type: "error",
        },
        {
          inputs: [],
          name: "LandNotEmpty",
          type: "error",
        },
        {
          inputs: [],
          name: "NotLandOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "NotReadyToHarvest",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToCleanUp",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToWithdraw",
          type: "error",
        },
        {
          inputs: [],
          name: "OnlyOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [],
          name: "SeedNotConfigured",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "WrongCleanupPayment",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "fruitToken",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxCapacity",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maturationTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "rotTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "cleanupCost",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "harvestYield",
              type: "uint256",
            },
          ],
          name: "FarmConfigAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "cleaner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "cost",
              type: "uint256",
            },
          ],
          name: "LandCleaned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "harvester",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "fruitAmount",
              type: "uint256",
            },
          ],
          name: "LandHarvested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "planter",
              type: "address",
            },
          ],
          name: "SeedsPlanted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawal",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxCapacity",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maturationTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "rotTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "cleanupCost",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "harvestYield",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "fruitName",
              type: "string",
            },
            {
              internalType: "string",
              name: "fruitSymbol",
              type: "string",
            },
          ],
          name: "addFarmConfig",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
          ],
          name: "cleanUp",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "dishMarket",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "farmConfigs",
          outputs: [
            {
              internalType: "uint256",
              name: "maxCapacity",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maturationTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "rotTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "cleanupCost",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "harvestYield",
              type: "uint256",
            },
            {
              internalType: "contract FruitToken",
              name: "fruitToken",
              type: "address",
            },
            {
              internalType: "bool",
              name: "configured",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "fruitToSeedId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
          ],
          name: "fruitToken",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
          ],
          name: "getLandState",
          outputs: [
            {
              internalType: "enum FarmManager.LandState",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
          ],
          name: "harvest",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
          ],
          name: "harvestYield",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "isFruitToken",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "landAuction",
          outputs: [
            {
              internalType: "contract LandAuction",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "plant",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "plots",
          outputs: [
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "seedAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "plantedAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "hasPlanting",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "needsCleanup",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "seedShop",
          outputs: [
            {
              internalType: "contract SeedShop",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_dishMarket",
              type: "address",
            },
          ],
          name: "setDishMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawFees",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 748,
    },
    LandAuction: {
      address: "0xFD471836031dc5108809D173A067e8486B9047A3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AllLandsSold",
          type: "error",
        },
        {
          inputs: [],
          name: "AuctionHasEnded",
          type: "error",
        },
        {
          inputs: [],
          name: "AuctionStillInProgress",
          type: "error",
        },
        {
          inputs: [],
          name: "BidMustBePositive",
          type: "error",
        },
        {
          inputs: [],
          name: "BidMustExceedCurrentHighest",
          type: "error",
        },
        {
          inputs: [],
          name: "NoActiveAuction",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToWithdraw",
          type: "error",
        },
        {
          inputs: [],
          name: "OnlyOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [],
          name: "AllLandsSoldOut",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "winner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "AuctionSettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "firstBidder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "endTime",
              type: "uint256",
            },
          ],
          name: "AuctionStarted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "landId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "bidder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "NewHighestBid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "bidder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawal",
          type: "event",
        },
        {
          inputs: [],
          name: "AUCTION_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TOTAL_LANDS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "auctionActive",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "auctionEndTime",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "bid",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "currentLandId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "dishMarket",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "highestBid",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "highestBidder",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "landOwner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "pendingWithdrawals",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_dishMarket",
              type: "address",
            },
          ],
          name: "setDishMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "settleAuction",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "timeRemaining",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawRefund",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 726,
    },
    SeedShop: {
      address: "0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "NothingToWithdraw",
          type: "error",
        },
        {
          inputs: [],
          name: "OnlyOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "PriceMustBePositive",
          type: "error",
        },
        {
          inputs: [],
          name: "QuantityMustBePositive",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [],
          name: "SeedNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "WrongETHAmount",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "symbol",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "SeedAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "quantity",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalPaid",
              type: "uint256",
            },
          ],
          name: "SeedPurchased",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawal",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "addSeed",
          outputs: [
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "quantity",
              type: "uint256",
            },
          ],
          name: "buy",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "dishMarket",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "seedCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
          ],
          name: "seedPrice",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "seedId",
              type: "uint256",
            },
          ],
          name: "seedToken",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "seeds",
          outputs: [
            {
              internalType: "contract SeedToken",
              name: "token",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "exists",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_dishMarket",
              type: "address",
            },
          ],
          name: "setDishMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 727,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
